apps = {
    "notepad": "notepad",
    "calculator": "calc",
    "paint": "mspaint",
    "wordpad": "write",
    "cmd": "cmd",
    "powershell": "powershell",
    "taskmanager": "taskmgr",
    "control panel": "control",
    "settings": "start ms-settings:",
    "file explorer": "explorer",
    "explorer": "explorer",
    "edge": "msedge",
    "chrome": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
    "brave": "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe",
    "media player": "wmplayer",
    "vlc": "C:\\Program Files\\VideoLAN\\VLC\\vlc.exe",
    "spotify": "spotify",
    "camera": "start microsoft.windows.camera:",
    "snipping tool": "snippingtool",
    "photos": "start microsoft.photos:",
    "vs code": "C:\\Users\\%USERNAME%\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
    "pycharm": "C:\\Program Files\\JetBrains\\PyCharm\\bin\\pycharm64.exe",
    "omen gaming hub": "start shell:AppsFolder\\AD2F1837.OMENCommandCenter_qmba6cd70vzyy!App",
    "downloads": "explorer shell:Downloads",
    "documents": "explorer shell:Documents",
    "desktop": "explorer shell:Desktop",
    "antigravity": "C:\\Users\\SHAGUFTA\\AppData\\Local\\Programs\\Antigravity\\Antigravity.exe",
    "registry editor": "regedit",
    "device manager": "devmgmt.msc",
    "disk management": "diskmgmt.msc",
}